base_model: facebook/xglm-564M

model_type: XGLMForCausalLM
tokenizer_type: XGLMTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

max_steps: 200
pretraining_dataset:
  path: uonlp/CulturaX
  name: or
  # type: completion
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./xgml-model-out

sequence_len: 4096
sample_packing: true

wandb_project: xgml_pretrain_odia
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 10
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false

warmup_steps: 10
evals_per_epoch:
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
